eights = len([1 for i in range(10000) for j in str(i) if j == '8'])
print(eights)

# print('8 :', eights)
# print('8 :', [eight_count(str(i)) for i in range(100)])
# print('8 :', sum([eight_count(str(i)) for i in range(10000)]))
# print('8 :', sum([str(i).count('8') for i in range(10000)]))
# print('8 :', [8 for i in range(100) for c in str(i) if c == '8'])
# print('8 :', len([8 for i in range(10000) for c in str(i) if c == '8']))
# print('8 :', ''.join([str(i) for i in range(100)]))
# print('8 :', re.findall(r'8', ''.join([str(i) for i in range(100)])))
# print('8 :', len(re.findall(r'8', ''.join([str(i) for i in range(10000)]))))
# print('8 :', ''.join([str(i) for i in range(10000)]).count('8'))
# print('8 :', list(range(10)))
# print('8 :', str(list(range(10000))).count('8'))
# print('[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'.count('8'))
